export const enum GroupeRisque {
  PERSONNE_VULNERABLE = 'PERSONNE_VULNERABLE',

  CORPS_MEDICAL = 'CORPS_MEDICAL',

  CONTACT_PERSONNE_VULNERABLE = 'CONTACT_PERSONNE_VULNERABLE',

  INSTITUTION_COMMUNAUTAIRE = 'INSTITUTION_COMMUNAUTAIRE',

  PERSONNE_SAINE = 'PERSONNE_SAINE',
}
